local humanoidRootPart, rightUpperArm, rightUpperArmMotor6d, leftUpperLeg, leftUpperLegMotor6d, leftMiddleLeg, leftMiddleLegMotor6d, leftLowerArm, leftLowerArmMotor6d, rightUpperLeg, rightUpperLegMotor6d, rightLowerArm, rightLowerArmMotor6d, rightMiddleLeg, rightMiddleLegMotor6d, tail, tailMotor6d, leftUpperArm, leftUpperArmMotor6d, leftLowerLeg, leftLowerLegMotor6d, head, headMotor6d, torso, torsoMotor6d, leftFoot, leftFootMotor6d, rightLowerLeg, rightLowerLegMotor6d, rightFoot, rightFootMotor6d, rightHand, rightHandMotor6d, rootPart, weldConstraint, leftHand, leftHandMotor6d

local wildberryDelight = Instance.new("Model")
wildberryDelight.Name = "WildberryDelight"
do
	local soundMute = Instance.new("LocalScript")
	soundMute.Name = "SoundMute"
	soundMute.Parent = wildberryDelight
	humanoidRootPart = Instance.new("Part")
	humanoidRootPart.CollisionGroup = "Player"
	humanoidRootPart.Name = "HumanoidRootPart"
	humanoidRootPart.Transparency = 1
	humanoidRootPart.Size = Vector3.new(2, 2, 1)
	humanoidRootPart.CustomPhysicalProperties = PhysicalProperties.new(15, 1, 0.3, 1, 1, 1)
	humanoidRootPart.CFrame = CFrame.new(Vector3.new(-62.3893, 2.3401, 63.4064)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	do
		local particleThing = Instance.new("ParticleEmitter")
		particleThing.Name = "ParticleThing"
		particleThing.Texture = "rbxassetid://18850392282"
		particleThing.Rate = 0.75
		particleThing.LightInfluence = 0.5
		particleThing.Acceleration = Vector3.yAxis * 0.1
		particleThing.SpreadAngle = Vector2.one * 100
		particleThing.Size = NumberSequence.new(0)
		particleThing.Lifetime = NumberRange.new(5)
		particleThing.Color = ColorSequence.new(Color3.fromRGB(184, 167, 127), Color3.fromRGB(184, 167, 127))
		particleThing.Parent = humanoidRootPart
		local particleThing_2 = Instance.new("ParticleEmitter")
		particleThing_2.Name = "ParticleThing"
		particleThing_2.Texture = "rbxassetid://18850392282"
		particleThing_2.Rate = 0.75
		particleThing_2.LightInfluence = 0.5
		particleThing_2.Enabled = false
		particleThing_2.Acceleration = Vector3.yAxis * 0.1
		particleThing_2.SpreadAngle = Vector2.one * 100
		particleThing_2.Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 1), NumberSequenceKeypoint.new(0.0846, 0.3499), NumberSequenceKeypoint.new(0.1357, 0.3437), NumberSequenceKeypoint.new(0.716, 0.3874), NumberSequenceKeypoint.new(1, 1)})
		particleThing_2.Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0), NumberSequenceKeypoint.new(0.4956, 0.2499, 0.125), NumberSequenceKeypoint.new(1, 0)})
		particleThing_2.Lifetime = NumberRange.new(5)
		particleThing_2.Color = ColorSequence.new(Color3.fromRGB(184, 167, 127), Color3.fromRGB(184, 167, 127))
		particleThing_2.Parent = humanoidRootPart
		local stickerOverride = Instance.new("Attachment")
		stickerOverride.Name = "StickerOverride"
		stickerOverride.CFrame = CFrame.new(Vector3.new(0, 6.686, -0.053))
		stickerOverride.Parent = humanoidRootPart
		local bubbleChat = Instance.new("Attachment")
		bubbleChat.Name = "BubbleChat"
		bubbleChat.CFrame = CFrame.new(Vector3.new(0, 3.2391, -0.053))
		bubbleChat.Parent = humanoidRootPart
	end
	humanoidRootPart.Parent = wildberryDelight
	local initialPoses = Instance.new("Folder")
	initialPoses.Name = "InitialPoses"
	do
		local cocoaWildberryDelightComposited = Instance.new("CFrameValue")
		cocoaWildberryDelightComposited.Name = "Cocoa_WildberryDelight_Composited"
		cocoaWildberryDelightComposited.Parent = initialPoses
		local cocoaWildberryDelightOriginal = Instance.new("CFrameValue")
		cocoaWildberryDelightOriginal.Name = "Cocoa_WildberryDelight_Original"
		cocoaWildberryDelightOriginal.Value = CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		cocoaWildberryDelightOriginal.Parent = initialPoses
		local cocoaWildberryDelightInitial = Instance.new("CFrameValue")
		cocoaWildberryDelightInitial.Name = "Cocoa_WildberryDelight_Initial"
		cocoaWildberryDelightInitial.Value = CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		cocoaWildberryDelightInitial.Parent = initialPoses
		local rightUpperArmComposited = Instance.new("CFrameValue")
		rightUpperArmComposited.Name = "RightUpperArm_Composited"
		rightUpperArmComposited.Parent = initialPoses
		local rightUpperArmOriginal = Instance.new("CFrameValue")
		rightUpperArmOriginal.Name = "RightUpperArm_Original"
		rightUpperArmOriginal.Parent = initialPoses
		local rightUpperArmInitial = Instance.new("CFrameValue")
		rightUpperArmInitial.Name = "RightUpperArm_Initial"
		rightUpperArmInitial.Parent = initialPoses
		local leftMiddleLegComposited = Instance.new("CFrameValue")
		leftMiddleLegComposited.Name = "LeftMiddleLeg_Composited"
		leftMiddleLegComposited.Parent = initialPoses
		local leftMiddleLegOriginal = Instance.new("CFrameValue")
		leftMiddleLegOriginal.Name = "LeftMiddleLeg_Original"
		leftMiddleLegOriginal.Parent = initialPoses
		local leftMiddleLegInitial = Instance.new("CFrameValue")
		leftMiddleLegInitial.Name = "LeftMiddleLeg_Initial"
		leftMiddleLegInitial.Parent = initialPoses
		local leftUpperLegComposited = Instance.new("CFrameValue")
		leftUpperLegComposited.Name = "LeftUpperLeg_Composited"
		leftUpperLegComposited.Parent = initialPoses
		local leftUpperLegOriginal = Instance.new("CFrameValue")
		leftUpperLegOriginal.Name = "LeftUpperLeg_Original"
		leftUpperLegOriginal.Parent = initialPoses
		local leftUpperLegInitial = Instance.new("CFrameValue")
		leftUpperLegInitial.Name = "LeftUpperLeg_Initial"
		leftUpperLegInitial.Parent = initialPoses
		local leftLowerArmComposited = Instance.new("CFrameValue")
		leftLowerArmComposited.Name = "LeftLowerArm_Composited"
		leftLowerArmComposited.Parent = initialPoses
		local leftLowerArmOriginal = Instance.new("CFrameValue")
		leftLowerArmOriginal.Name = "LeftLowerArm_Original"
		leftLowerArmOriginal.Parent = initialPoses
		local leftLowerArmInitial = Instance.new("CFrameValue")
		leftLowerArmInitial.Name = "LeftLowerArm_Initial"
		leftLowerArmInitial.Parent = initialPoses
		local rightUpperLegComposited = Instance.new("CFrameValue")
		rightUpperLegComposited.Name = "RightUpperLeg_Composited"
		rightUpperLegComposited.Parent = initialPoses
		local rightUpperLegOriginal = Instance.new("CFrameValue")
		rightUpperLegOriginal.Name = "RightUpperLeg_Original"
		rightUpperLegOriginal.Parent = initialPoses
		local rightUpperLegInitial = Instance.new("CFrameValue")
		rightUpperLegInitial.Name = "RightUpperLeg_Initial"
		rightUpperLegInitial.Parent = initialPoses
		local rightLowerArmComposited = Instance.new("CFrameValue")
		rightLowerArmComposited.Name = "RightLowerArm_Composited"
		rightLowerArmComposited.Parent = initialPoses
		local rightLowerArmOriginal = Instance.new("CFrameValue")
		rightLowerArmOriginal.Name = "RightLowerArm_Original"
		rightLowerArmOriginal.Parent = initialPoses
		local rightLowerArmInitial = Instance.new("CFrameValue")
		rightLowerArmInitial.Name = "RightLowerArm_Initial"
		rightLowerArmInitial.Parent = initialPoses
		local rightMiddleLegComposited = Instance.new("CFrameValue")
		rightMiddleLegComposited.Name = "RightMiddleLeg_Composited"
		rightMiddleLegComposited.Parent = initialPoses
		local rightMiddleLegOriginal = Instance.new("CFrameValue")
		rightMiddleLegOriginal.Name = "RightMiddleLeg_Original"
		rightMiddleLegOriginal.Parent = initialPoses
		local rightMiddleLegInitial = Instance.new("CFrameValue")
		rightMiddleLegInitial.Name = "RightMiddleLeg_Initial"
		rightMiddleLegInitial.Parent = initialPoses
		local tailComposited = Instance.new("CFrameValue")
		tailComposited.Name = "Tail_Composited"
		tailComposited.Parent = initialPoses
		local tailOriginal = Instance.new("CFrameValue")
		tailOriginal.Name = "Tail_Original"
		tailOriginal.Parent = initialPoses
		local tailInitial = Instance.new("CFrameValue")
		tailInitial.Name = "Tail_Initial"
		tailInitial.Parent = initialPoses
		local leftUpperArmComposited = Instance.new("CFrameValue")
		leftUpperArmComposited.Name = "LeftUpperArm_Composited"
		leftUpperArmComposited.Parent = initialPoses
		local leftUpperArmOriginal = Instance.new("CFrameValue")
		leftUpperArmOriginal.Name = "LeftUpperArm_Original"
		leftUpperArmOriginal.Parent = initialPoses
		local leftUpperArmInitial = Instance.new("CFrameValue")
		leftUpperArmInitial.Name = "LeftUpperArm_Initial"
		leftUpperArmInitial.Parent = initialPoses
		local leftLowerLegComposited = Instance.new("CFrameValue")
		leftLowerLegComposited.Name = "LeftLowerLeg_Composited"
		leftLowerLegComposited.Parent = initialPoses
		local leftLowerLegOriginal = Instance.new("CFrameValue")
		leftLowerLegOriginal.Name = "LeftLowerLeg_Original"
		leftLowerLegOriginal.Parent = initialPoses
		local leftLowerLegInitial = Instance.new("CFrameValue")
		leftLowerLegInitial.Name = "LeftLowerLeg_Initial"
		leftLowerLegInitial.Parent = initialPoses
		local torsoComposited = Instance.new("CFrameValue")
		torsoComposited.Name = "Torso_Composited"
		torsoComposited.Parent = initialPoses
		local torsoOriginal = Instance.new("CFrameValue")
		torsoOriginal.Name = "Torso_Original"
		torsoOriginal.Parent = initialPoses
		local torsoInitial = Instance.new("CFrameValue")
		torsoInitial.Name = "Torso_Initial"
		torsoInitial.Parent = initialPoses
		local headComposited = Instance.new("CFrameValue")
		headComposited.Name = "Head_Composited"
		headComposited.Parent = initialPoses
		local headOriginal = Instance.new("CFrameValue")
		headOriginal.Name = "Head_Original"
		headOriginal.Parent = initialPoses
		local headInitial = Instance.new("CFrameValue")
		headInitial.Name = "Head_Initial"
		headInitial.Parent = initialPoses
		local rightLowerLegComposited = Instance.new("CFrameValue")
		rightLowerLegComposited.Name = "RightLowerLeg_Composited"
		rightLowerLegComposited.Parent = initialPoses
		local rightLowerLegOriginal = Instance.new("CFrameValue")
		rightLowerLegOriginal.Name = "RightLowerLeg_Original"
		rightLowerLegOriginal.Parent = initialPoses
		local rightLowerLegInitial = Instance.new("CFrameValue")
		rightLowerLegInitial.Name = "RightLowerLeg_Initial"
		rightLowerLegInitial.Parent = initialPoses
		local rightHandComposited = Instance.new("CFrameValue")
		rightHandComposited.Name = "RIghtHand_Composited"
		rightHandComposited.Parent = initialPoses
		local rightHandOriginal = Instance.new("CFrameValue")
		rightHandOriginal.Name = "RIghtHand_Original"
		rightHandOriginal.Parent = initialPoses
		local rightHandInitial = Instance.new("CFrameValue")
		rightHandInitial.Name = "RIghtHand_Initial"
		rightHandInitial.Parent = initialPoses
		local leftHandComposited = Instance.new("CFrameValue")
		leftHandComposited.Name = "LeftHand_Composited"
		leftHandComposited.Parent = initialPoses
		local leftHandOriginal = Instance.new("CFrameValue")
		leftHandOriginal.Name = "LeftHand_Original"
		leftHandOriginal.Parent = initialPoses
		local leftHandInitial = Instance.new("CFrameValue")
		leftHandInitial.Name = "LeftHand_Initial"
		leftHandInitial.Parent = initialPoses
		local rightFootComposited = Instance.new("CFrameValue")
		rightFootComposited.Name = "RightFoot_Composited"
		rightFootComposited.Parent = initialPoses
		local rightFootOriginal = Instance.new("CFrameValue")
		rightFootOriginal.Name = "RightFoot_Original"
		rightFootOriginal.Parent = initialPoses
		local rightFootInitial = Instance.new("CFrameValue")
		rightFootInitial.Name = "RightFoot_Initial"
		rightFootInitial.Parent = initialPoses
		local leftFootComposited = Instance.new("CFrameValue")
		leftFootComposited.Name = "LeftFoot_Composited"
		leftFootComposited.Parent = initialPoses
		local leftFootOriginal = Instance.new("CFrameValue")
		leftFootOriginal.Name = "LeftFoot_Original"
		leftFootOriginal.Parent = initialPoses
		local leftFootInitial = Instance.new("CFrameValue")
		leftFootInitial.Name = "LeftFoot_Initial"
		leftFootInitial.Parent = initialPoses
		local rootComposited = Instance.new("CFrameValue")
		rootComposited.Name = "root_Composited"
		rootComposited.Value = CFrame.new(Vector3.new(0, 1.4061, -0.0056)) * CFrame.fromEulerAnglesXYZ(math.rad(86.439), math.rad(-90), 0)
		rootComposited.Parent = initialPoses
		local rootOriginal = Instance.new("CFrameValue")
		rootOriginal.Name = "root_Original"
		rootOriginal.Value = CFrame.new(Vector3.new(0, 1.4061, 0.0055)) * CFrame.fromEulerAnglesXYZ(math.rad(-86.4391), math.rad(90), 0)
		rootOriginal.Parent = initialPoses
		local rootInitial = Instance.new("CFrameValue")
		rootInitial.Name = "root_Initial"
		rootInitial.Value = CFrame.new(Vector3.new(0, 1.4061, 0.0055)) * CFrame.fromEulerAnglesXYZ(math.rad(-86.4391), math.rad(90), 0)
		rootInitial.Parent = initialPoses
		local torsoComposited_2 = Instance.new("CFrameValue")
		torsoComposited_2.Name = "torso_Composited"
		torsoComposited_2.Value = CFrame.new(Vector3.new(0, 1.7837, 0.0076)) * CFrame.fromEulerAnglesXYZ(math.rad(90), math.rad(-90), 0)
		torsoComposited_2.Parent = initialPoses
		local torsoOriginal_2 = Instance.new("CFrameValue")
		torsoOriginal_2.Name = "torso_Original"
		torsoOriginal_2.Value = CFrame.new(Vector3.new(-0.3761, 0.0366, 0)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(-3.5567))
		torsoOriginal_2.Parent = initialPoses
		local torsoInitial_2 = Instance.new("CFrameValue")
		torsoInitial_2.Name = "torso_Initial"
		torsoInitial_2.Value = CFrame.new(Vector3.new(-0.3761, 0.0366, 0)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(-3.5567))
		torsoInitial_2.Parent = initialPoses
		local chestComposited = Instance.new("CFrameValue")
		chestComposited.Name = "chest_Composited"
		chestComposited.Value = CFrame.new(Vector3.new(0, 2.1926, 0.0076)) * CFrame.fromEulerAnglesXYZ(math.rad(87.5478), math.rad(-90), 0)
		chestComposited.Parent = initialPoses
		local chestOriginal = Instance.new("CFrameValue")
		chestOriginal.Name = "chest_Original"
		chestOriginal.Value = CFrame.new(Vector3.new(-0.4089, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(2.4533))
		chestOriginal.Parent = initialPoses
		local chestInitial = Instance.new("CFrameValue")
		chestInitial.Name = "chest_Initial"
		chestInitial.Value = CFrame.new(Vector3.new(-0.4089, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(2.4533))
		chestInitial.Parent = initialPoses
		local headComposited_2 = Instance.new("CFrameValue")
		headComposited_2.Name = "head_Composited"
		headComposited_2.Value = CFrame.new(Vector3.new(0, 2.7967, -0.0312)) * CFrame.fromEulerAnglesXYZ(math.rad(87.5478), math.rad(-90), 0)
		headComposited_2.Parent = initialPoses
		local headOriginal_2 = Instance.new("CFrameValue")
		headOriginal_2.Name = "head_Original"
		headOriginal_2.Value = CFrame.new(Vector3.new(-0.6053, -0.013, 0))
		headOriginal_2.Parent = initialPoses
		local headInitial_2 = Instance.new("CFrameValue")
		headInitial_2.Name = "head_Initial"
		headInitial_2.Value = CFrame.new(Vector3.new(-0.6053, -0.013, 0))
		headInitial_2.Parent = initialPoses
		local lEarComposited = Instance.new("CFrameValue")
		lEarComposited.Name = "L_Ear_Composited"
		lEarComposited.Value = CFrame.new(Vector3.new(-0.13, 5.2211, 0.7151)) * CFrame.fromEulerAnglesXYZ(math.rad(-115.2485), math.rad(-0.0019), math.rad(78.6337))
		lEarComposited.Parent = initialPoses
		local lEarOriginal = Instance.new("CFrameValue")
		lEarOriginal.Name = "L_Ear_Original"
		lEarOriginal.Value = CFrame.new(Vector3.new(-2.3903, 0.8493, 0.1299)) * CFrame.fromEulerAnglesXYZ(math.rad(89.9976), math.rad(-67.2027), math.rad(-11.3655))
		lEarOriginal.Parent = initialPoses
		local lEarInitial = Instance.new("CFrameValue")
		lEarInitial.Name = "L_Ear_Initial"
		lEarInitial.Value = CFrame.new(Vector3.new(-2.3903, 0.8493, 0.1299)) * CFrame.fromEulerAnglesXYZ(math.rad(89.9976), math.rad(-67.2027), math.rad(-11.3655))
		lEarInitial.Parent = initialPoses
		local lEarEndComposited = Instance.new("CFrameValue")
		lEarEndComposited.Name = "L_Ear_end_Composited"
		lEarEndComposited.Value = CFrame.new(Vector3.new(-0.3148, 5.6131, 1.5464)) * CFrame.fromEulerAnglesXYZ(math.rad(-55.6564), math.rad(-0.0009), math.rad(84.013))
		lEarEndComposited.Parent = initialPoses
		local lEarEndOriginal = Instance.new("CFrameValue")
		lEarEndOriginal.Name = "L_Ear_end_Original"
		lEarEndOriginal.Value = CFrame.new(Vector3.new(-0.9375, 0, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(18.558), math.rad(-57.7221), math.rad(15.667))
		lEarEndOriginal.Parent = initialPoses
		local lEarEndInitial = Instance.new("CFrameValue")
		lEarEndInitial.Name = "L_Ear_end_Initial"
		lEarEndInitial.Value = CFrame.new(Vector3.new(-0.9375, 0, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(18.558), math.rad(-57.7221), math.rad(15.667))
		lEarEndInitial.Parent = initialPoses
		local lEarEnd1Composited = Instance.new("CFrameValue")
		lEarEnd1Composited.Name = "L_Ear_end1_Composited"
		lEarEnd1Composited.Value = CFrame.new(Vector3.new(-0.4616, 4.8237, 2.702)) * CFrame.fromEulerAnglesXYZ(math.rad(-8.6657), 0, math.rad(87.7274))
		lEarEnd1Composited.Parent = initialPoses
		local lEarEnd1Original = Instance.new("CFrameValue")
		lEarEnd1Original.Name = "L_Ear_end1_Original"
		lEarEnd1Original.Value = CFrame.new(Vector3.xAxis * -1.4072) * CFrame.fromEulerAnglesXYZ(math.rad(6.3835), math.rad(-46.6571), math.rad(6.4663))
		lEarEnd1Original.Parent = initialPoses
		local lEarEnd1Initial = Instance.new("CFrameValue")
		lEarEnd1Initial.Name = "L_Ear_end1_Initial"
		lEarEnd1Initial.Value = CFrame.new(Vector3.xAxis * -1.4072) * CFrame.fromEulerAnglesXYZ(math.rad(6.3835), math.rad(-46.6571), math.rad(6.4663))
		lEarEnd1Initial.Parent = initialPoses
		local lEarEnd2Composited = Instance.new("CFrameValue")
		lEarEnd2Composited.Name = "L_Ear_end2_Composited"
		lEarEnd2Composited.Value = CFrame.new(Vector3.new(-0.5404, 2.8609, 3.0011)) * CFrame.fromEulerAnglesXYZ(math.rad(-8.6657), 0, math.rad(87.7274))
		lEarEnd2Composited.Parent = initialPoses
		local lEarEnd2Original = Instance.new("CFrameValue")
		lEarEnd2Original.Name = "L_Ear_end2_Original"
		lEarEnd2Original.Value = CFrame.new(Vector3.new(-1.9871, 0, 0))
		lEarEnd2Original.Parent = initialPoses
		local lEarEnd2Initial = Instance.new("CFrameValue")
		lEarEnd2Initial.Name = "L_Ear_end2_Initial"
		lEarEnd2Initial.Value = CFrame.new(Vector3.new(-1.9871, 0, 0))
		lEarEnd2Initial.Parent = initialPoses
		local rEarComposited = Instance.new("CFrameValue")
		rEarComposited.Name = "R_Ear_Composited"
		rEarComposited.Value = CFrame.new(Vector3.new(0.1299, 5.2211, 0.7151)) * CFrame.fromEulerAnglesXYZ(math.rad(-115.0361), math.rad(0.0019), math.rad(104.0195))
		rEarComposited.Parent = initialPoses
		local rEarOriginal = Instance.new("CFrameValue")
		rEarOriginal.Name = "R_Ear_Original"
		rEarOriginal.Value = CFrame.new(Vector3.new(-2.3903, 0.8493, -0.13)) * CFrame.fromEulerAnglesXYZ(math.rad(90.0069), math.rad(-67.4204), math.rad(14.0269))
		rEarOriginal.Parent = initialPoses
		local rEarInitial = Instance.new("CFrameValue")
		rEarInitial.Name = "R_Ear_Initial"
		rEarInitial.Value = CFrame.new(Vector3.new(-2.3903, 0.8493, -0.13)) * CFrame.fromEulerAnglesXYZ(math.rad(90.0069), math.rad(-67.4204), math.rad(14.0269))
		rEarInitial.Parent = initialPoses
		local rEarEndComposited = Instance.new("CFrameValue")
		rEarEndComposited.Name = "R_Ear_end_Composited"
		rEarEndComposited.Value = CFrame.new(Vector3.new(0.3595, 5.61, 1.5478)) * CFrame.fromEulerAnglesXYZ(math.rad(-53.8095), 0, math.rad(95.1322))
		rEarEndComposited.Parent = initialPoses
		local rEarEndOriginal = Instance.new("CFrameValue")
		rEarEndOriginal.Name = "R_Ear_end_Original"
		rEarEndOriginal.Value = CFrame.new(Vector3.new(-0.9473, 0, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(-23.8057), math.rad(-58.2559), math.rad(-22.2859))
		rEarEndOriginal.Parent = initialPoses
		local rEarEndInitial = Instance.new("CFrameValue")
		rEarEndInitial.Name = "R_Ear_end_Initial"
		rEarEndInitial.Value = CFrame.new(Vector3.new(-0.9473, 0, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(-23.8057), math.rad(-58.2559), math.rad(-22.2859))
		rEarEndInitial.Parent = initialPoses
		local rEarEnd1Composited = Instance.new("CFrameValue")
		rEarEnd1Composited.Name = "R_Ear_end1_Composited"
		rEarEnd1Composited.Value = CFrame.new(Vector3.new(0.4822, 4.8028, 2.651)) * CFrame.fromEulerAnglesXYZ(math.rad(-7.1448), 0, math.rad(92.8533))
		rEarEnd1Composited.Parent = initialPoses
		local rEarEnd1Original = Instance.new("CFrameValue")
		rEarEnd1Original.Name = "R_Ear_end1_Original"
		rEarEnd1Original.Value = CFrame.new(Vector3.new(-1.3726, 0, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(-5.4161), math.rad(-46.421), math.rad(-4.6025))
		rEarEnd1Original.Parent = initialPoses
		local rEarEnd1Initial = Instance.new("CFrameValue")
		rEarEnd1Initial.Name = "R_Ear_end1_Initial"
		rEarEnd1Initial.Value = CFrame.new(Vector3.new(-1.3726, 0, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(-5.4161), math.rad(-46.421), math.rad(-4.6025))
		rEarEnd1Initial.Parent = initialPoses
		local rEarEnd2Composited = Instance.new("CFrameValue")
		rEarEnd2Composited.Name = "R_Ear_end2_Composited"
		rEarEnd2Composited.Value = CFrame.new(Vector3.new(0.5819, 2.8172, 2.9)) * CFrame.fromEulerAnglesXYZ(math.rad(-7.1448), 0, math.rad(92.8533))
		rEarEnd2Composited.Parent = initialPoses
		local rEarEnd2Original = Instance.new("CFrameValue")
		rEarEnd2Original.Name = "R_Ear_end2_Original"
		rEarEnd2Original.Value = CFrame.new(Vector3.new(-2.0037, 0, 0))
		rEarEnd2Original.Parent = initialPoses
		local rEarEnd2Initial = Instance.new("CFrameValue")
		rEarEnd2Initial.Name = "R_Ear_end2_Initial"
		rEarEnd2Initial.Value = CFrame.new(Vector3.new(-2.0037, 0, 0))
		rEarEnd2Initial.Parent = initialPoses
		local lArmComposited = Instance.new("CFrameValue")
		lArmComposited.Name = "L_arm_Composited"
		lArmComposited.Value = CFrame.new(Vector3.new(-0.3729, 2.5455, -0.0067))
		lArmComposited.Parent = initialPoses
		local lArmOriginal = Instance.new("CFrameValue")
		lArmOriginal.Name = "L_arm_Original"
		lArmOriginal.Value = CFrame.new(Vector3.new(-0.3532, 0.0008, 0.3728)) * CFrame.fromEulerAnglesXYZ(math.rad(-89.9988), math.rad(2.4521), math.rad(89.9987))
		lArmOriginal.Parent = initialPoses
		local lArmInitial = Instance.new("CFrameValue")
		lArmInitial.Name = "L_arm_Initial"
		lArmInitial.Value = CFrame.new(Vector3.new(-0.3532, 0.0008, 0.3728)) * CFrame.fromEulerAnglesXYZ(math.rad(-89.9988), math.rad(2.4521), math.rad(89.9987))
		lArmInitial.Parent = initialPoses
		local lElbowComposited = Instance.new("CFrameValue")
		lElbowComposited.Name = "L_elbow_Composited"
		lElbowComposited.Value = CFrame.new(Vector3.new(-0.9729, 2.5455, -0.0067))
		lElbowComposited.Parent = initialPoses
		local lElbowOriginal = Instance.new("CFrameValue")
		lElbowOriginal.Name = "L_elbow_Original"
		lElbowOriginal.Value = CFrame.new(Vector3.xAxis * -0.6001)
		lElbowOriginal.Parent = initialPoses
		local lElbowInitial = Instance.new("CFrameValue")
		lElbowInitial.Name = "L_elbow_Initial"
		lElbowInitial.Value = CFrame.new(Vector3.xAxis * -0.6001)
		lElbowInitial.Parent = initialPoses
		local lHandComposited = Instance.new("CFrameValue")
		lHandComposited.Name = "L_hand_Composited"
		lHandComposited.Value = CFrame.new(Vector3.new(-1.4729, 2.5455, -0.0067))
		lHandComposited.Parent = initialPoses
		local lHandOriginal = Instance.new("CFrameValue")
		lHandOriginal.Name = "L_hand_Original"
		lHandOriginal.Value = CFrame.new(Vector3.xAxis * -0.5001)
		lHandOriginal.Parent = initialPoses
		local lHandInitial = Instance.new("CFrameValue")
		lHandInitial.Name = "L_hand_Initial"
		lHandInitial.Value = CFrame.new(Vector3.xAxis * -0.5001)
		lHandInitial.Parent = initialPoses
		local lFingerComposited = Instance.new("CFrameValue")
		lFingerComposited.Name = "L_finger_Composited"
		lFingerComposited.Value = CFrame.new(Vector3.new(-1.8755, 2.5455, -0.0067))
		lFingerComposited.Parent = initialPoses
		local lFingerOriginal = Instance.new("CFrameValue")
		lFingerOriginal.Name = "L_finger_Original"
		lFingerOriginal.Value = CFrame.new(Vector3.xAxis * -0.4027)
		lFingerOriginal.Parent = initialPoses
		local lFingerInitial = Instance.new("CFrameValue")
		lFingerInitial.Name = "L_finger_Initial"
		lFingerInitial.Value = CFrame.new(Vector3.xAxis * -0.4027)
		lFingerInitial.Parent = initialPoses
		local rArmComposited = Instance.new("CFrameValue")
		rArmComposited.Name = "R_arm_Composited"
		rArmComposited.Value = CFrame.new(Vector3.new(0.3732, 2.5455, -0.0067)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		rArmComposited.Parent = initialPoses
		local rArmOriginal = Instance.new("CFrameValue")
		rArmOriginal.Name = "R_arm_Original"
		rArmOriginal.Value = CFrame.new(Vector3.new(-0.3532, 0.0008, -0.3733)) * CFrame.fromEulerAnglesXYZ(math.rad(89.9987), math.rad(-2.4522), math.rad(89.9987))
		rArmOriginal.Parent = initialPoses
		local rArmInitial = Instance.new("CFrameValue")
		rArmInitial.Name = "R_arm_Initial"
		rArmInitial.Value = CFrame.new(Vector3.new(-0.3532, 0.0008, -0.3733)) * CFrame.fromEulerAnglesXYZ(math.rad(89.9987), math.rad(-2.4522), math.rad(89.9987))
		rArmInitial.Parent = initialPoses
		local rElbowComposited = Instance.new("CFrameValue")
		rElbowComposited.Name = "R_elbow_Composited"
		rElbowComposited.Value = CFrame.new(Vector3.new(0.9732, 2.5455, -0.0067)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		rElbowComposited.Parent = initialPoses
		local rElbowOriginal = Instance.new("CFrameValue")
		rElbowOriginal.Name = "R_elbow_Original"
		rElbowOriginal.Value = CFrame.new(Vector3.xAxis * -0.6001)
		rElbowOriginal.Parent = initialPoses
		local rElbowInitial = Instance.new("CFrameValue")
		rElbowInitial.Name = "R_elbow_Initial"
		rElbowInitial.Value = CFrame.new(Vector3.xAxis * -0.6001)
		rElbowInitial.Parent = initialPoses
		local rHandComposited = Instance.new("CFrameValue")
		rHandComposited.Name = "R_hand_Composited"
		rHandComposited.Value = CFrame.new(Vector3.new(1.4732, 2.5455, -0.0067)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		rHandComposited.Parent = initialPoses
		local rHandOriginal = Instance.new("CFrameValue")
		rHandOriginal.Name = "R_hand_Original"
		rHandOriginal.Value = CFrame.new(Vector3.xAxis * -0.5)
		rHandOriginal.Parent = initialPoses
		local rHandInitial = Instance.new("CFrameValue")
		rHandInitial.Name = "R_hand_Initial"
		rHandInitial.Value = CFrame.new(Vector3.xAxis * -0.5)
		rHandInitial.Parent = initialPoses
		local rFingerComposited = Instance.new("CFrameValue")
		rFingerComposited.Name = "R_finger_Composited"
		rFingerComposited.Value = CFrame.new(Vector3.new(1.8904, 2.5455, -0.0067)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		rFingerComposited.Parent = initialPoses
		local rFingerOriginal = Instance.new("CFrameValue")
		rFingerOriginal.Name = "R_finger_Original"
		rFingerOriginal.Value = CFrame.new(Vector3.xAxis * -0.4172)
		rFingerOriginal.Parent = initialPoses
		local rFingerInitial = Instance.new("CFrameValue")
		rFingerInitial.Name = "R_finger_Initial"
		rFingerInitial.Value = CFrame.new(Vector3.xAxis * -0.4172)
		rFingerInitial.Parent = initialPoses
		local rSkirtJntComposited = Instance.new("CFrameValue")
		rSkirtJntComposited.Name = "R_skirt_jnt_Composited"
		rSkirtJntComposited.Value = CFrame.new(Vector3.new(0.4513, 1.5923, -0.556))
		rSkirtJntComposited.Parent = initialPoses
		local rSkirtJntOriginal = Instance.new("CFrameValue")
		rSkirtJntOriginal.Name = "R_skirt_jnt_Original"
		rSkirtJntOriginal.Value = CFrame.new(Vector3.new(0.1914, -0.5636, -0.4514)) * CFrame.fromEulerAnglesXYZ(math.rad(-90), 0, math.rad(90))
		rSkirtJntOriginal.Parent = initialPoses
		local rSkirtJntInitial = Instance.new("CFrameValue")
		rSkirtJntInitial.Name = "R_skirt_jnt_Initial"
		rSkirtJntInitial.Value = CFrame.new(Vector3.new(0.1914, -0.5636, -0.4514)) * CFrame.fromEulerAnglesXYZ(math.rad(-90), 0, math.rad(90))
		rSkirtJntInitial.Parent = initialPoses
		local lSkirtJntComposited = Instance.new("CFrameValue")
		lSkirtJntComposited.Name = "L_skirt_jnt_Composited"
		lSkirtJntComposited.Value = CFrame.new(Vector3.new(-0.4722, 1.5923, -0.556))
		lSkirtJntComposited.Parent = initialPoses
		local lSkirtJntOriginal = Instance.new("CFrameValue")
		lSkirtJntOriginal.Name = "L_skirt_jnt_Original"
		lSkirtJntOriginal.Value = CFrame.new(Vector3.new(0.1914, -0.5636, 0.4721)) * CFrame.fromEulerAnglesXYZ(math.rad(-90), 0, math.rad(90))
		lSkirtJntOriginal.Parent = initialPoses
		local lSkirtJntInitial = Instance.new("CFrameValue")
		lSkirtJntInitial.Name = "L_skirt_jnt_Initial"
		lSkirtJntInitial.Value = CFrame.new(Vector3.new(0.1914, -0.5636, 0.4721)) * CFrame.fromEulerAnglesXYZ(math.rad(-90), 0, math.rad(90))
		lSkirtJntInitial.Parent = initialPoses
		local lLegComposited = Instance.new("CFrameValue")
		lLegComposited.Name = "L_leg_Composited"
		lLegComposited.Value = CFrame.new(Vector3.new(-0.4193, 1.7976, 0.0241)) * CFrame.fromEulerAnglesXYZ(math.rad(179.6934), math.rad(-83.293), math.rad(-95.7357))
		lLegComposited.Parent = initialPoses
		local lLegOriginal = Instance.new("CFrameValue")
		lLegOriginal.Name = "L_leg_Original"
		lLegOriginal.Value = CFrame.new(Vector3.new(-0.3889, 0.0538, 0.4192)) * CFrame.fromEulerAnglesXYZ(math.rad(6.6912), math.rad(-0.381), math.rad(171.0357))
		lLegOriginal.Parent = initialPoses
		local lLegInitial = Instance.new("CFrameValue")
		lLegInitial.Name = "L_leg_Initial"
		lLegInitial.Value = CFrame.new(Vector3.new(-0.3889, 0.0538, 0.4192)) * CFrame.fromEulerAnglesXYZ(math.rad(6.6912), math.rad(-0.381), math.rad(171.0357))
		lLegInitial.Parent = initialPoses
		local lKneeComposited = Instance.new("CFrameValue")
		lKneeComposited.Name = "L_knee_Composited"
		lKneeComposited.Value = CFrame.new(Vector3.new(-0.379, 0.7922, -0.0077)) * CFrame.fromEulerAnglesXYZ(math.rad(-0.3013), math.rad(83.2964), math.rad(49.4607))
		lKneeComposited.Parent = initialPoses
		local lKneeOriginal = Instance.new("CFrameValue")
		lKneeOriginal.Name = "L_knee_Original"
		lKneeOriginal.Value = CFrame.new(Vector3.new(-1.0043, -0.0591, -0.0358)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-46.2695))
		lKneeOriginal.Parent = initialPoses
		local lKneeInitial = Instance.new("CFrameValue")
		lKneeInitial.Name = "L_knee_Initial"
		lKneeInitial.Value = CFrame.new(Vector3.new(-1.0043, -0.0591, -0.0358)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-46.2695))
		lKneeInitial.Parent = initialPoses
		local lFootComposited = Instance.new("CFrameValue")
		lFootComposited.Name = "L_foot_Composited"
		lFootComposited.Value = CFrame.new(Vector3.new(-0.3892, 0.6408, 0.1261)) * CFrame.fromEulerAnglesXYZ(math.rad(179.7041), math.rad(-83.2969), math.rad(-104.1859))
		lFootComposited.Parent = initialPoses
		local lFootOriginal = Instance.new("CFrameValue")
		lFootOriginal.Name = "L_foot_Original"
		lFootOriginal.Value = CFrame.new(Vector3.new(-0.2023, 0.0024, 0.0054)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-54.731))
		lFootOriginal.Parent = initialPoses
		local lFootInitial = Instance.new("CFrameValue")
		lFootInitial.Name = "L_foot_Initial"
		lFootInitial.Value = CFrame.new(Vector3.new(-0.2023, 0.0024, 0.0054)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-54.731))
		lFootInitial.Parent = initialPoses
		local lFootEndComposited = Instance.new("CFrameValue")
		lFootEndComposited.Name = "L_foot_end_Composited"
		lFootEndComposited.Value = CFrame.new(Vector3.new(-0.38, 0.1762, 0.0227)) * CFrame.fromEulerAnglesXYZ(math.rad(-179.8347), math.rad(-79.0099), math.rad(-103.6431))
		lFootEndComposited.Parent = initialPoses
		local lFootEndOriginal = Instance.new("CFrameValue")
		lFootEndOriginal.Name = "L_foot_end_Original"
		lFootEndOriginal.Value = CFrame.new(Vector3.new(-0.476, -0.0109, 0.0032)) * CFrame.fromEulerAnglesXYZ(math.rad(-4.175), math.rad(-0.9622), math.rad(0.054))
		lFootEndOriginal.Parent = initialPoses
		local lFootEndInitial = Instance.new("CFrameValue")
		lFootEndInitial.Name = "L_foot_end_Initial"
		lFootEndInitial.Value = CFrame.new(Vector3.new(-0.476, -0.0109, 0.0032)) * CFrame.fromEulerAnglesXYZ(math.rad(-4.175), math.rad(-0.9622), math.rad(0.054))
		lFootEndInitial.Parent = initialPoses
		local rLegComposited = Instance.new("CFrameValue")
		rLegComposited.Name = "R_leg_Composited"
		rLegComposited.Value = CFrame.new(Vector3.new(0.4419, 1.7976, 0.024)) * CFrame.fromEulerAnglesXYZ(math.rad(-0.0738), math.rad(-80.4866), math.rad(84.2373))
		rLegComposited.Parent = initialPoses
		local rLegOriginal = Instance.new("CFrameValue")
		rLegOriginal.Name = "R_leg_Original"
		rLegOriginal.Value = CFrame.new(Vector3.new(-0.3889, 0.0538, -0.442)) * CFrame.fromEulerAnglesXYZ(math.rad(-9.4966), math.rad(0.5764), math.rad(170.8017))
		rLegOriginal.Parent = initialPoses
		local rLegInitial = Instance.new("CFrameValue")
		rLegInitial.Name = "R_leg_Initial"
		rLegInitial.Value = CFrame.new(Vector3.new(-0.3889, 0.0538, -0.442)) * CFrame.fromEulerAnglesXYZ(math.rad(-9.4966), math.rad(0.5764), math.rad(170.8017))
		rLegInitial.Parent = initialPoses
		local rKneeComposited = Instance.new("CFrameValue")
		rKneeComposited.Name = "R_knee_Composited"
		rKneeComposited.Value = CFrame.new(Vector3.new(0.3777, 0.7924, -0.0048)) * CFrame.fromEulerAnglesXYZ(math.rad(179.9487), math.rad(80.4869), math.rad(-130.5283))
		rKneeComposited.Parent = initialPoses
		local rKneeOriginal = Instance.new("CFrameValue")
		rKneeOriginal.Name = "R_knee_Original"
		rKneeOriginal.Value = CFrame.new(Vector3.new(-1.0042, -0.0608, 0.0583)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-46.2641))
		rKneeOriginal.Parent = initialPoses
		local rKneeInitial = Instance.new("CFrameValue")
		rKneeInitial.Name = "R_knee_Initial"
		rKneeInitial.Value = CFrame.new(Vector3.new(-1.0042, -0.0608, 0.0583)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-46.2641))
		rKneeInitial.Parent = initialPoses
		local rFootComposited = Instance.new("CFrameValue")
		rFootComposited.Name = "R_foot_Composited"
		rFootComposited.Value = CFrame.new(Vector3.new(0.3944, 0.6403, 0.1277)) * CFrame.fromEulerAnglesXYZ(math.rad(14.3408), math.rad(9.219), math.rad(87.6407))
		rFootComposited.Parent = initialPoses
		local rFootOriginal = Instance.new("CFrameValue")
		rFootOriginal.Name = "R_foot_Original"
		rFootOriginal.Value = CFrame.new(Vector3.new(-0.2023, 0.0024, -0.0055)) * CFrame.fromEulerAnglesXYZ(math.rad(-89.9942), math.rad(-54.7335), math.rad(0.003))
		rFootOriginal.Parent = initialPoses
		local rFootInitial = Instance.new("CFrameValue")
		rFootInitial.Name = "R_foot_Initial"
		rFootInitial.Value = CFrame.new(Vector3.new(-0.2023, 0.0024, -0.0055)) * CFrame.fromEulerAnglesXYZ(math.rad(-89.9942), math.rad(-54.7335), math.rad(0.003))
		rFootInitial.Parent = initialPoses
		local rFootEndComposited = Instance.new("CFrameValue")
		rFootEndComposited.Name = "R_foot_end_Composited"
		rFootEndComposited.Value = CFrame.new(Vector3.new(0.3799, 0.1762, 0.0227)) * CFrame.fromEulerAnglesXYZ(math.rad(14.4621), math.rad(13.3922), math.rad(86.6605))
		rFootEndComposited.Parent = initialPoses
		local rFootEndOriginal = Instance.new("CFrameValue")
		rFootEndOriginal.Name = "R_foot_end_Original"
		rFootEndOriginal.Value = CFrame.new(Vector3.new(-0.476, -0.0033, 0.0108)) * CFrame.fromEulerAnglesXYZ(math.rad(4.1758), math.rad(0.054), math.rad(-0.9622))
		rFootEndOriginal.Parent = initialPoses
		local rFootEndInitial = Instance.new("CFrameValue")
		rFootEndInitial.Name = "R_foot_end_Initial"
		rFootEndInitial.Value = CFrame.new(Vector3.new(-0.476, -0.0033, 0.0108)) * CFrame.fromEulerAnglesXYZ(math.rad(4.1758), math.rad(0.054), math.rad(-0.9622))
		rFootEndInitial.Parent = initialPoses
		local tailComposited_2 = Instance.new("CFrameValue")
		tailComposited_2.Name = "tail_Composited"
		tailComposited_2.Value = CFrame.new(Vector3.new(0, 1.748, 0.5578)) * CFrame.fromEulerAnglesXYZ(math.rad(-90), 0, math.rad(90))
		tailComposited_2.Parent = initialPoses
		local tailOriginal_2 = Instance.new("CFrameValue")
		tailOriginal_2.Name = "tail_Original"
		tailOriginal_2.Value = CFrame.new(Vector3.new(-0.3063, 0.5834, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(-90.0717), math.rad(-86.439), math.rad(179.9325))
		tailOriginal_2.Parent = initialPoses
		local tailInitial_2 = Instance.new("CFrameValue")
		tailInitial_2.Name = "tail_Initial"
		tailInitial_2.Value = CFrame.new(Vector3.new(-0.3063, 0.5834, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(-90.0717), math.rad(-86.439), math.rad(179.9325))
		tailInitial_2.Parent = initialPoses
	end
	initialPoses.Parent = wildberryDelight
	local config = Instance.new("Configuration")
	config.Name = "Config"
	do
		local sprint = Instance.new("Script")
		sprint.Name = "Sprint"
		sprint.Parent = config
		local normalTexture = Instance.new("Decal")
		normalTexture.Name = "NormalTexture"
		normalTexture.Texture = "rbxassetid://84063381517655"
		normalTexture.Parent = config
		local blinkTexture = Instance.new("Decal")
		blinkTexture.Name = "BlinkTexture"
		blinkTexture.Texture = "rbxassetid://103991320583591"
		blinkTexture.Parent = config
		local hurtTexture = Instance.new("Decal")
		hurtTexture.Name = "HurtTexture"
		hurtTexture.Texture = "rbxassetid://115414173032208"
		hurtTexture.Parent = config
		local characterName = Instance.new("StringValue")
		characterName.Name = "CharacterName"
		characterName.Value = "Cocoa_WildberryDelight_Rig"
		characterName.Parent = config
		local moduleName = Instance.new("StringValue")
		moduleName.Name = "ModuleName"
		moduleName.Value = "Cocoa_WildberryDelight_Rig"
		moduleName.Parent = config
	end
	config.Parent = wildberryDelight
	local humanoid = Instance.new("Humanoid")
	humanoid.HipHeight = 1.2999
	humanoid.NameDisplayDistance = 0
	humanoid.HealthDisplayType = Enum.HumanoidHealthDisplayType.AlwaysOff
	do
		local animator = Instance.new("Animator")
		animator.Parent = humanoid
	end
	humanoid.Parent = wildberryDelight
	local animations = Instance.new("Configuration")
	animations.Name = "Animations"
	do
		local run = Instance.new("Animation")
		run.Name = "Run"
		run.AnimationId = "rbxassetid://106296018216054"
		run.Parent = animations
		local walk = Instance.new("Animation")
		walk.Name = "Walk"
		walk.AnimationId = "rbxassetid://122786131919623"
		walk.Parent = animations
		local idle = Instance.new("Animation")
		idle.Name = "Idle"
		idle.AnimationId = "rbxassetid://124966645905392"
		idle.Parent = animations
		local quirk = Instance.new("Animation")
		quirk.Name = "Quirk"
		quirk.AnimationId = "rbxassetid://135206913100225"
		quirk.Parent = animations
		local decode = Instance.new("Animation")
		decode.Name = "Decode"
		decode.AnimationId = "rbxassetid://78766397787381"
		decode.Parent = animations
		local ability = Instance.new("Animation")
		ability.Name = "Ability"
		ability.AnimationId = "rbxassetid://139178228834787"
		ability.Parent = animations
		local placeChocolate = Instance.new("Animation")
		placeChocolate.Name = "PlaceChocolate"
		placeChocolate.AnimationId = "rbxassetid://96543133816454"
		placeChocolate.Parent = animations
	end
	animations.Parent = wildberryDelight
	local decoding = Instance.new("BoolValue")
	decoding.Name = "Decoding"
	decoding.Parent = wildberryDelight
	local stats = Instance.new("Folder")
	stats.Name = "Stats"
	do
		local holdingSprint = Instance.new("BoolValue")
		holdingSprint.Name = "HoldingSprint"
		holdingSprint.Parent = stats
		local sprinting = Instance.new("BoolValue")
		sprinting.Name = "Sprinting"
		sprinting.Parent = stats
	end
	stats.Parent = wildberryDelight
	local inLobby = Instance.new("BoolValue")
	inLobby.Name = "InLobby"
	inLobby.Parent = wildberryDelight
	rightUpperArm = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://96710853742556", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	rightUpperArm.TextureID = "rbxassetid://84063381517655"
	rightUpperArm.CollisionGroup = "Player"
	rightUpperArm.Name = "RightUpperArm"
	rightUpperArm.CanTouch = false
	rightUpperArm.CanQuery = false
	rightUpperArm.Massless = true
	rightUpperArm.CanCollide = false
	rightUpperArm.Size = Vector3.new(0.8248, 0.3791, 0.3898)
	rightUpperArm.CFrame = CFrame.new(Vector3.new(-62.3957, 4.9043, 64.0507)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	rightUpperArm.PivotOffset = CFrame.identity
	do
		rightUpperArmMotor6d = Instance.new("Motor6D")
		rightUpperArmMotor6d.Name = "RightUpperArmMotor6D"
		rightUpperArmMotor6d.MaxVelocity = 0.1
		rightUpperArmMotor6d.C0 = CFrame.new(Vector3.new(0.6442, 2.5641, 0.0064))
		rightUpperArmMotor6d.Parent = rightUpperArm
	end
	rightUpperArm.Parent = wildberryDelight
	leftUpperLeg = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://74018022466773", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	leftUpperLeg.TextureID = "rbxassetid://84063381517655"
	leftUpperLeg.CollisionGroup = "Player"
	leftUpperLeg.Name = "LeftUpperLeg"
	leftUpperLeg.CanTouch = false
	leftUpperLeg.CanQuery = false
	leftUpperLeg.Massless = true
	leftUpperLeg.CanCollide = false
	leftUpperLeg.Size = Vector3.new(0.7097, 1.2488, 0.6882)
	leftUpperLeg.CFrame = CFrame.new(Vector3.new(-62.3686, 3.6156, 63.0043)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	leftUpperLeg.PivotOffset = CFrame.new(Vector3.new(-0.0014, -0.0174, 0.0029))
	do
		leftUpperLegMotor6d = Instance.new("Motor6D")
		leftUpperLegMotor6d.Name = "LeftUpperLegMotor6D"
		leftUpperLegMotor6d.MaxVelocity = 0.1
		leftUpperLegMotor6d.C0 = CFrame.new(Vector3.new(-0.4021, 1.2754, -0.0208))
		leftUpperLegMotor6d.Parent = leftUpperLeg
	end
	leftUpperLeg.Parent = wildberryDelight
	leftMiddleLeg = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://75454885133645", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	leftMiddleLeg.TextureID = "rbxassetid://84063381517655"
	leftMiddleLeg.CollisionGroup = "Player"
	leftMiddleLeg.Name = "LeftMiddleLeg"
	leftMiddleLeg.CanTouch = false
	leftMiddleLeg.CanQuery = false
	leftMiddleLeg.Massless = true
	leftMiddleLeg.CanCollide = false
	leftMiddleLeg.Size = Vector3.new(0.3636, 0.4017, 0.4449)
	leftMiddleLeg.CFrame = CFrame.new(Vector3.new(-62.4449, 3.0676, 63.0726)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	leftMiddleLeg.PivotOffset = CFrame.new(Vector3.new(-0.0072, 0.0155, -0.0022))
	do
		leftMiddleLegMotor6d = Instance.new("Motor6D")
		leftMiddleLegMotor6d.Name = "LeftMiddleLegMotor6D"
		leftMiddleLegMotor6d.MaxVelocity = 0.1
		leftMiddleLegMotor6d.C0 = CFrame.new(Vector3.new(-0.3338, 0.7274, 0.0555))
		leftMiddleLegMotor6d.Parent = leftMiddleLeg
	end
	leftMiddleLeg.Parent = wildberryDelight
	leftLowerArm = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://124813827446474", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	leftLowerArm.TextureID = "rbxassetid://84063381517655"
	leftLowerArm.CollisionGroup = "Player"
	leftLowerArm.Name = "LeftLowerArm"
	leftLowerArm.CanTouch = false
	leftLowerArm.CanQuery = false
	leftLowerArm.Massless = true
	leftLowerArm.CanCollide = false
	leftLowerArm.Size = Vector3.new(0.7131, 0.3405, 0.3485)
	leftLowerArm.CFrame = CFrame.new(Vector3.new(-62.3957, 4.9043, 62.1852)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	leftLowerArm.PivotOffset = CFrame.new(Vector3.new(-0.0248, 0, 0))
	do
		leftLowerArmMotor6d = Instance.new("Motor6D")
		leftLowerArmMotor6d.Name = "LeftLowerArmMotor6D"
		leftLowerArmMotor6d.MaxVelocity = 0.1
		leftLowerArmMotor6d.C0 = CFrame.new(Vector3.new(-1.2212, 2.5641, 0.0063))
		leftLowerArmMotor6d.Parent = leftLowerArm
	end
	leftLowerArm.Parent = wildberryDelight
	rightUpperLeg = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://125212817818554", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	rightUpperLeg.TextureID = "rbxassetid://84063381517655"
	rightUpperLeg.CollisionGroup = "Player"
	rightUpperLeg.Name = "RightUpperLeg"
	rightUpperLeg.CanTouch = false
	rightUpperLeg.CanQuery = false
	rightUpperLeg.Massless = true
	rightUpperLeg.CanCollide = false
	rightUpperLeg.Size = Vector3.new(0.7097, 1.2488, 0.6882)
	rightUpperLeg.CFrame = CFrame.new(Vector3.new(-62.3686, 3.6156, 63.8085)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	rightUpperLeg.PivotOffset = CFrame.new(Vector3.new(0.0013, -0.0174, 0.0029))
	do
		rightUpperLegMotor6d = Instance.new("Motor6D")
		rightUpperLegMotor6d.Name = "RightUpperLegMotor6D"
		rightUpperLegMotor6d.MaxVelocity = 0.1
		rightUpperLegMotor6d.C0 = CFrame.new(Vector3.new(0.402, 1.2754, -0.0208))
		rightUpperLegMotor6d.Parent = rightUpperLeg
	end
	rightUpperLeg.Parent = wildberryDelight
	rightLowerArm = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://81492048989013", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	rightLowerArm.TextureID = "rbxassetid://84063381517655"
	rightLowerArm.CollisionGroup = "Player"
	rightLowerArm.Name = "RightLowerArm"
	rightLowerArm.CanTouch = false
	rightLowerArm.CanQuery = false
	rightLowerArm.Massless = true
	rightLowerArm.CanCollide = false
	rightLowerArm.Size = Vector3.new(0.7131, 0.3405, 0.3485)
	rightLowerArm.CFrame = CFrame.new(Vector3.new(-62.3957, 4.9043, 64.6276)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	rightLowerArm.PivotOffset = CFrame.new(Vector3.new(0.0247, 0, 0))
	do
		rightLowerArmMotor6d = Instance.new("Motor6D")
		rightLowerArmMotor6d.Name = "RightLowerArmMotor6D"
		rightLowerArmMotor6d.MaxVelocity = 0.1
		rightLowerArmMotor6d.C0 = CFrame.new(Vector3.new(1.2211, 2.5641, 0.0063))
		rightLowerArmMotor6d.Parent = rightLowerArm
	end
	rightLowerArm.Parent = wildberryDelight
	rightMiddleLeg = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://119284467605497", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	rightMiddleLeg.TextureID = "rbxassetid://84063381517655"
	rightMiddleLeg.CollisionGroup = "Player"
	rightMiddleLeg.Name = "RightMiddleLeg"
	rightMiddleLeg.CanTouch = false
	rightMiddleLeg.CanQuery = false
	rightMiddleLeg.Massless = true
	rightMiddleLeg.CanCollide = false
	rightMiddleLeg.Size = Vector3.new(0.3636, 0.4017, 0.4449)
	rightMiddleLeg.CFrame = CFrame.new(Vector3.new(-62.4449, 3.0676, 63.7402)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	rightMiddleLeg.PivotOffset = CFrame.new(Vector3.new(0.0071, 0.0155, -0.0022))
	do
		rightMiddleLegMotor6d = Instance.new("Motor6D")
		rightMiddleLegMotor6d.Name = "RightMiddleLegMotor6D"
		rightMiddleLegMotor6d.MaxVelocity = 0.1
		rightMiddleLegMotor6d.C0 = CFrame.new(Vector3.new(0.3337, 0.7274, 0.0555))
		rightMiddleLegMotor6d.Parent = rightMiddleLeg
	end
	rightMiddleLeg.Parent = wildberryDelight
	tail = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://130774880814514", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	tail.TextureID = "rbxassetid://84063381517655"
	tail.CollisionGroup = "Player"
	tail.Name = "Tail"
	tail.Massless = true
	tail.CanCollide = false
	tail.CanTouch = false
	tail.CanQuery = false
	tail.Size = Vector3.new(0.6797, 0.6801, 0.6169)
	tail.CFrame = CFrame.new(Vector3.new(-63.318, 4.0443, 63.4043)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	do
		tailMotor6d = Instance.new("Motor6D")
		tailMotor6d.Name = "TailMotor6D"
		tailMotor6d.MaxVelocity = 0.1
		tailMotor6d.C0 = CFrame.new(Vector3.new(-0.0022, 1.7041, 0.9286))
		tailMotor6d.Parent = tail
	end
	tail.Parent = wildberryDelight
	leftUpperArm = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://86412887467256", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	leftUpperArm.TextureID = "rbxassetid://84063381517655"
	leftUpperArm.CollisionGroup = "Player"
	leftUpperArm.Name = "LeftUpperArm"
	leftUpperArm.CanTouch = false
	leftUpperArm.CanQuery = false
	leftUpperArm.Massless = true
	leftUpperArm.CanCollide = false
	leftUpperArm.Size = Vector3.new(0.8248, 0.3791, 0.3898)
	leftUpperArm.CFrame = CFrame.new(Vector3.new(-62.3957, 4.9043, 62.7621)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	leftUpperArm.PivotOffset = CFrame.identity
	do
		leftUpperArmMotor6d = Instance.new("Motor6D")
		leftUpperArmMotor6d.Name = "LeftUpperArmMotor6D"
		leftUpperArmMotor6d.MaxVelocity = 0.1
		leftUpperArmMotor6d.C0 = CFrame.new(Vector3.new(-0.6443, 2.5641, 0.0064))
		leftUpperArmMotor6d.Parent = leftUpperArm
	end
	leftUpperArm.Parent = wildberryDelight
	leftLowerLeg = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://84976403753751", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	leftLowerLeg.TextureID = "rbxassetid://84063381517655"
	leftLowerLeg.CollisionGroup = "Player"
	leftLowerLeg.Name = "LeftLowerLeg"
	leftLowerLeg.CanTouch = false
	leftLowerLeg.CanQuery = false
	leftLowerLeg.Massless = true
	leftLowerLeg.CanCollide = false
	leftLowerLeg.Size = Vector3.new(0.6013, 0.6929, 0.5225)
	leftLowerLeg.CFrame = CFrame.new(Vector3.new(-62.4298, 2.702, 63.079)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	leftLowerLeg.PivotOffset = CFrame.new(Vector3.new(-0.0216, 0.0312, 0.0056))
	do
		leftLowerLegMotor6d = Instance.new("Motor6D")
		leftLowerLegMotor6d.Name = "LeftLowerLegMotor6D"
		leftLowerLegMotor6d.MaxVelocity = 0.1
		leftLowerLegMotor6d.C0 = CFrame.new(Vector3.new(-0.3275, 0.3618, 0.0405))
		leftLowerLegMotor6d.Parent = leftLowerLeg
	end
	leftLowerLeg.Parent = wildberryDelight
	head = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://70798227193598", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	head.TextureID = "rbxassetid://84063381517655"
	head.CollisionGroup = "Player"
	head.Name = "Head"
	head.CanTouch = false
	head.CanQuery = false
	head.Massless = true
	head.CanCollide = false
	head.Size = Vector3.new(2.6657, 4.6876, 5.0861)
	head.CFrame = CFrame.new(Vector3.new(-63.3344, 5.9411, 63.4064)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	head.PivotOffset = CFrame.identity
	do
		headMotor6d = Instance.new("Motor6D")
		headMotor6d.Name = "HeadMotor6D"
		headMotor6d.MaxVelocity = 0.1
		headMotor6d.C0 = CFrame.new(Vector3.new(0, 3.6009, 0.945))
		headMotor6d.Parent = head
	end
	head.Parent = wildberryDelight
	torso = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://95628404453395", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	torso.TextureID = "rbxassetid://84063381517655"
	torso.Name = "Torso"
	torso.CollisionGroup = "IgnoreCollision"
	torso.Massless = true
	torso.CanTouch = false
	torso.CanQuery = false
	torso.Size = Vector3.new(2.0496, 1.8412, 1.8022)
	torso.CFrame = CFrame.new(Vector3.new(-62.3831, 4.3565, 63.4064)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	torso.PivotOffset = CFrame.new(Vector3.new(0, 0.0884, -0.0051))
	do
		torsoMotor6d = Instance.new("Motor6D")
		torsoMotor6d.Name = "TorsoMotor6D"
		torsoMotor6d.MaxVelocity = 0.1
		torsoMotor6d.C0 = CFrame.new(Vector3.new(0, 2.0163, -0.0063))
		torsoMotor6d.Parent = torso
	end
	torso.Parent = wildberryDelight
	leftFoot = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://112599576025920", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	leftFoot.TextureID = "rbxassetid://84063381517655"
	leftFoot.CollisionGroup = "Player"
	leftFoot.Name = "LeftFoot"
	leftFoot.CanTouch = false
	leftFoot.CanQuery = false
	leftFoot.Massless = true
	leftFoot.CanCollide = false
	leftFoot.Size = Vector3.new(0.5907, 0.3098, 0.6957)
	leftFoot.CFrame = CFrame.new(Vector3.new(-62.2675, 2.4951, 63.0527)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	leftFoot.PivotOffset = CFrame.new(Vector3.new(0, 0.0119, 0))
	do
		leftFootMotor6d = Instance.new("Motor6D")
		leftFootMotor6d.Name = "LeftFootMotor6D"
		leftFootMotor6d.MaxVelocity = 0.1
		leftFootMotor6d.C0 = CFrame.new(Vector3.new(-0.3538, 0.1549, -0.1219))
		leftFootMotor6d.Parent = leftFoot
	end
	leftFoot.Parent = wildberryDelight
	rightLowerLeg = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://126479089287841", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	rightLowerLeg.TextureID = "rbxassetid://84063381517655"
	rightLowerLeg.CollisionGroup = "Player"
	rightLowerLeg.Name = "RightLowerLeg"
	rightLowerLeg.CanTouch = false
	rightLowerLeg.CanQuery = false
	rightLowerLeg.Massless = true
	rightLowerLeg.CanCollide = false
	rightLowerLeg.Size = Vector3.new(0.6013, 0.6929, 0.5225)
	rightLowerLeg.CFrame = CFrame.new(Vector3.new(-62.4298, 2.702, 63.7338)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	rightLowerLeg.PivotOffset = CFrame.new(Vector3.new(0.0215, 0.0312, 0.0056))
	do
		rightLowerLegMotor6d = Instance.new("Motor6D")
		rightLowerLegMotor6d.Name = "RightLowerLegMotor6D"
		rightLowerLegMotor6d.MaxVelocity = 0.1
		rightLowerLegMotor6d.C0 = CFrame.new(Vector3.new(0.3274, 0.3618, 0.0405))
		rightLowerLegMotor6d.Parent = rightLowerLeg
	end
	rightLowerLeg.Parent = wildberryDelight
	rightFoot = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://106588064259206", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	rightFoot.TextureID = "rbxassetid://84063381517655"
	rightFoot.CollisionGroup = "Player"
	rightFoot.Name = "RightFoot"
	rightFoot.CanTouch = false
	rightFoot.CanQuery = false
	rightFoot.Massless = true
	rightFoot.CanCollide = false
	rightFoot.Size = Vector3.new(0.5907, 0.3098, 0.6957)
	rightFoot.CFrame = CFrame.new(Vector3.new(-62.2675, 2.4951, 63.7601)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	rightFoot.PivotOffset = CFrame.new(Vector3.new(0, 0.0119, 0))
	do
		rightFootMotor6d = Instance.new("Motor6D")
		rightFootMotor6d.Name = "RightFootMotor6D"
		rightFootMotor6d.MaxVelocity = 0.1
		rightFootMotor6d.C0 = CFrame.new(Vector3.new(0.3537, 0.1549, -0.1219))
		rightFootMotor6d.Parent = rightFoot
	end
	rightFoot.Parent = wildberryDelight
	rightHand = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://139900053408315", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	rightHand.TextureID = "rbxassetid://84063381517655"
	rightHand.CollisionGroup = "Player"
	rightHand.Name = "RIghtHand"
	rightHand.CanTouch = false
	rightHand.CanQuery = false
	rightHand.Massless = true
	rightHand.CanCollide = false
	rightHand.Size = Vector3.new(0.8171, 0.2739, 0.69)
	rightHand.CFrame = CFrame.new(Vector3.new(-62.3239, 4.9043, 65.1694)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	rightHand.PivotOffset = CFrame.identity
	do
		rightHandMotor6d = Instance.new("Motor6D")
		rightHandMotor6d.Name = "RIghtHandMotor6D"
		rightHandMotor6d.MaxVelocity = 0.1
		rightHandMotor6d.C0 = CFrame.new(Vector3.new(1.7629, 2.5641, -0.0655))
		rightHandMotor6d.Parent = rightHand
	end
	rightHand.Parent = wildberryDelight
	rootPart = Instance.new("Part")
	rootPart.Name = "RootPart"
	rootPart.CollisionGroup = "Player"
	rootPart.Transparency = 1
	rootPart.CanTouch = false
	rootPart.CanQuery = false
	rootPart.CanCollide = false
	rootPart.Massless = true
	rootPart.Size = Vector3.new(2, 2, 1)
	rootPart.CFrame = CFrame.new(Vector3.new(-62.3893, 2.3401, 63.4064)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	do
		local root = Instance.new("Bone")
		root.Name = "root"
		root.SecondaryAxis = Vector3.new(0, 0.0621, 0.998)
		root.Axis = Vector3.new(0, -0.9981, 0.0621)
		root.CFrame = CFrame.new(Vector3.yAxis * -0.95) * CFrame.fromEulerAnglesXYZ(math.rad(86.439), math.rad(-90), 0)
		do
			local torso_2 = Instance.new("Bone")
			torso_2.Name = "torso"
			torso_2.SecondaryAxis = Vector3.new(0.062, 0.998, 0)
			torso_2.Axis = Vector3.new(0.998, -0.0621, 0)
			torso_2.CFrame = CFrame.new(Vector3.new(-0.3761, 0.0366, 0)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(-3.5567))
			do
				local chest = Instance.new("Bone")
				chest.Name = "chest"
				chest.SecondaryAxis = Vector3.new(-0.0429, 0.999, 0)
				chest.Axis = Vector3.new(0.999, 0.0428, 0)
				chest.CFrame = CFrame.new(Vector3.new(-0.4089, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(2.4533))
				do
					local head_2 = Instance.new("Bone")
					head_2.Name = "head"
					head_2.CFrame = CFrame.new(Vector3.new(-0.6053, -0.013, 0))
					do
						local lEar = Instance.new("Bone")
						lEar.Name = "L_Ear"
						lEar.SecondaryAxis = Vector3.new(0.0763, -0.1817, 0.9803)
						lEar.Axis = Vector3.new(0.3798, -0.9039, -0.1971)
						lEar.CFrame = CFrame.new(Vector3.new(-2.3903, 0.8493, 0.1299)) * CFrame.fromEulerAnglesXYZ(math.rad(89.9976), math.rad(-67.2027), math.rad(-11.3655))
						do
							local lEarEnd = Instance.new("Bone")
							lEarEnd.Name = "L_Ear_end"
							lEarEnd.SecondaryAxis = Vector3.new(-0.1443, 0.9854, 0.0899)
							lEarEnd.Axis = Vector3.new(0.5141, -0.0031, 0.8576)
							lEarEnd.CFrame = CFrame.new(Vector3.new(-0.9375, 0, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(18.558), math.rad(-57.7221), math.rad(15.667))
							do
								local lEarEnd1 = Instance.new("Bone")
								lEarEnd1.Name = "L_Ear_end1"
								lEarEnd1.SecondaryAxis = Vector3.new(-0.0773, 0.9965, 0.029)
								lEarEnd1.Axis = Vector3.new(0.6819, 0.0315, 0.7306)
								lEarEnd1.CFrame = CFrame.new(Vector3.new(-1.4072, 0, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(6.3835), math.rad(-46.6571), math.rad(6.4663))
								do
									local lEarEnd2 = Instance.new("Bone")
									lEarEnd2.Name = "L_Ear_end2"
									lEarEnd2.CFrame = CFrame.new(Vector3.xAxis * -1.9871)
									lEarEnd2.Parent = lEarEnd1
								end
								lEarEnd1.Parent = lEarEnd
							end
							lEarEnd.Parent = lEar
						end
						lEar.Parent = head_2
						local rEar = Instance.new("Bone")
						rEar.Name = "R_Ear"
						rEar.SecondaryAxis = Vector3.new(-0.0931, 0.2236, 0.9702)
						rEar.Axis = Vector3.new(0.3725, -0.8959, 0.2422)
						rEar.CFrame = CFrame.new(Vector3.new(-2.3903, 0.8493, -0.13)) * CFrame.fromEulerAnglesXYZ(math.rad(90.0069), math.rad(-67.4204), math.rad(14.0269))
						do
							local rEarEnd = Instance.new("Bone")
							rEarEnd.Name = "R_Ear_end"
							rEarEnd.SecondaryAxis = Vector3.new(0.1995, 0.9767, -0.0785)
							rEarEnd.Axis = Vector3.new(0.4868, -0.0294, 0.873)
							rEarEnd.CFrame = CFrame.new(Vector3.xAxis * -0.9473) * CFrame.fromEulerAnglesXYZ(math.rad(-23.8057), math.rad(-58.2559), math.rad(-22.2859))
							do
								local rEarEnd1 = Instance.new("Bone")
								rEarEnd1.Name = "R_Ear_end1"
								rEarEnd1.SecondaryAxis = Vector3.new(0.0553, 0.9978, -0.0363)
								rEarEnd1.Axis = Vector3.new(0.6871, -0.0118, 0.7264)
								rEarEnd1.CFrame = CFrame.new(Vector3.new(-1.3726, 0, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(-5.4161), math.rad(-46.421), math.rad(-4.6025))
								do
									local rEarEnd2 = Instance.new("Bone")
									rEarEnd2.Name = "R_Ear_end2"
									rEarEnd2.CFrame = CFrame.new(Vector3.new(-2.0037, 0, 0))
									rEarEnd2.Parent = rEarEnd1
								end
								rEarEnd1.Parent = rEarEnd
							end
							rEarEnd.Parent = rEar
						end
						rEar.Parent = head_2
					end
					head_2.Parent = chest
					local lArm = Instance.new("Bone")
					lArm.Name = "L_arm"
					lArm.SecondaryAxis = Vector3.new(-0.9991, 0.0427, 0)
					lArm.Axis = Vector3.new(0, 0, -1)
					lArm.CFrame = CFrame.new(Vector3.new(-0.3532, 0.0008, 0.3728)) * CFrame.fromEulerAnglesXYZ(math.rad(-89.9988), math.rad(2.4521), math.rad(89.9987))
					do
						local lElbow = Instance.new("Bone")
						lElbow.Name = "L_elbow"
						lElbow.CFrame = CFrame.new(Vector3.new(-0.6001, 0, 0))
						do
							local lHand = Instance.new("Bone")
							lHand.Name = "L_hand"
							lHand.CFrame = CFrame.new(Vector3.xAxis * -0.5001)
							do
								local lFinger = Instance.new("Bone")
								lFinger.Name = "L_finger"
								lFinger.CFrame = CFrame.new(Vector3.xAxis * -0.4027)
								lFinger.Parent = lHand
							end
							lHand.Parent = lElbow
						end
						lElbow.Parent = lArm
					end
					lArm.Parent = chest
					local rArm = Instance.new("Bone")
					rArm.Name = "R_arm"
					rArm.SecondaryAxis = Vector3.new(-0.9991, 0.0427, 0)
					rArm.Axis = Vector3.new(0, 0, 1)
					rArm.CFrame = CFrame.new(Vector3.new(-0.3532, 0.0008, -0.3733)) * CFrame.fromEulerAnglesXYZ(math.rad(89.9987), math.rad(-2.4522), math.rad(89.9987))
					do
						local rElbow = Instance.new("Bone")
						rElbow.Name = "R_elbow"
						rElbow.CFrame = CFrame.new(Vector3.new(-0.6001, 0, 0))
						do
							local rHand = Instance.new("Bone")
							rHand.Name = "R_hand"
							rHand.CFrame = CFrame.new(Vector3.xAxis * -0.5)
							do
								local rFinger = Instance.new("Bone")
								rFinger.Name = "R_finger"
								rFinger.CFrame = CFrame.new(Vector3.xAxis * -0.4172)
								rFinger.Parent = rHand
							end
							rHand.Parent = rElbow
						end
						rElbow.Parent = rArm
					end
					rArm.Parent = chest
				end
				chest.Parent = torso_2
				local rSkirtJnt = Instance.new("Bone")
				rSkirtJnt.Name = "R_skirt_jnt"
				rSkirtJnt.SecondaryAxis = -Vector3.xAxis
				rSkirtJnt.Axis = -Vector3.zAxis
				rSkirtJnt.CFrame = CFrame.new(Vector3.new(0.1914, -0.5636, -0.4514)) * CFrame.fromEulerAnglesXYZ(math.rad(-90), 0, math.rad(90))
				rSkirtJnt.Parent = torso_2
				local lSkirtJnt = Instance.new("Bone")
				lSkirtJnt.Name = "L_skirt_jnt"
				lSkirtJnt.SecondaryAxis = -Vector3.xAxis
				lSkirtJnt.Axis = -Vector3.zAxis
				lSkirtJnt.CFrame = CFrame.new(Vector3.new(0.1914, -0.5636, 0.4721)) * CFrame.fromEulerAnglesXYZ(math.rad(-90), 0, math.rad(90))
				lSkirtJnt.Parent = torso_2
			end
			torso_2.Parent = root
			local lLeg = Instance.new("Bone")
			lLeg.Name = "L_leg"
			lLeg.SecondaryAxis = Vector3.new(-0.1559, -0.981, -0.1162)
			lLeg.Axis = Vector3.new(-0.9878, 0.1555, 0.0116)
			lLeg.CFrame = CFrame.new(Vector3.new(-0.3889, 0.0538, 0.4192)) * CFrame.fromEulerAnglesXYZ(math.rad(6.6912), math.rad(-0.381), math.rad(171.0357))
			do
				local lKnee = Instance.new("Bone")
				lKnee.Name = "L_knee"
				lKnee.SecondaryAxis = Vector3.new(0.7225, -0.6913, 0)
				lKnee.Axis = Vector3.new(0.6912, 0.7225, 0)
				lKnee.CFrame = CFrame.new(Vector3.new(-1.0043, -0.0591, -0.0358)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-46.2695))
				do
					local lFoot = Instance.new("Bone")
					lFoot.Name = "L_foot"
					lFoot.SecondaryAxis = Vector3.new(0.8164, -0.5775, 0)
					lFoot.Axis = Vector3.new(0.5774, 0.8164, 0)
					lFoot.CFrame = CFrame.new(Vector3.new(-0.2023, 0.0024, 0.0054)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-54.731))
					do
						local lFootEnd = Instance.new("Bone")
						lFootEnd.Name = "L_foot_end"
						lFootEnd.SecondaryAxis = Vector3.new(-0.001, 0.9973, -0.0729)
						lFootEnd.Axis = Vector3.new(1, 0.0021, 0.0166)
						lFootEnd.CFrame = CFrame.new(Vector3.new(-0.476, -0.0109, 0.0032)) * CFrame.fromEulerAnglesXYZ(math.rad(-4.175), math.rad(-0.9622), math.rad(0.054))
						lFootEnd.Parent = lFoot
					end
					lFoot.Parent = lKnee
				end
				lKnee.Parent = lLeg
			end
			lLeg.Parent = root
			local rLeg = Instance.new("Bone")
			rLeg.Name = "R_leg"
			rLeg.SecondaryAxis = Vector3.new(-0.1599, -0.9734, 0.1644)
			rLeg.Axis = Vector3.new(-0.9871, 0.1592, -0.0166)
			rLeg.CFrame = CFrame.new(Vector3.new(-0.3889, 0.0538, -0.442)) * CFrame.fromEulerAnglesXYZ(math.rad(-9.4966), math.rad(0.5764), math.rad(170.8017))
			do
				local rKnee = Instance.new("Bone")
				rKnee.Name = "R_knee"
				rKnee.SecondaryAxis = Vector3.new(0.7225, -0.6914, 0)
				rKnee.Axis = Vector3.new(0.6913, 0.7225, 0)
				rKnee.CFrame = CFrame.new(Vector3.new(-1.0042, -0.0608, 0.0583)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-46.2641))
				do
					local rFoot = Instance.new("Bone")
					rFoot.Name = "R_foot"
					rFoot.SecondaryAxis = Vector3.new(0, 0, -1)
					rFoot.Axis = Vector3.new(0.5773, 0.8164, 0)
					rFoot.CFrame = CFrame.new(Vector3.new(-0.2023, 0.0024, -0.0055)) * CFrame.fromEulerAnglesXYZ(math.rad(-89.9942), math.rad(-54.7335), math.rad(0.003))
					do
						local rFootEnd = Instance.new("Bone")
						rFootEnd.Name = "R_foot_end"
						rFootEnd.SecondaryAxis = Vector3.new(0.0167, 0.9972, 0.0727)
						rFootEnd.Axis = Vector3.new(1, -0.0167, -0.0022)
						rFootEnd.CFrame = CFrame.new(Vector3.new(-0.476, -0.0033, 0.0108)) * CFrame.fromEulerAnglesXYZ(math.rad(4.1758), math.rad(0.054), math.rad(-0.9622))
						rFootEnd.Parent = rFoot
					end
					rFoot.Parent = rKnee
				end
				rKnee.Parent = rLeg
			end
			rLeg.Parent = root
			local tail_2 = Instance.new("Bone")
			tail_2.Name = "tail"
			tail_2.SecondaryAxis = Vector3.new(0, 0, 1)
			tail_2.Axis = Vector3.new(-0.0622, -0.9981, 0)
			tail_2.CFrame = CFrame.new(Vector3.new(-0.3063, 0.5834, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(-90.0718), math.rad(-86.439), math.rad(179.9325))
			tail_2.Parent = root
		end
		root.Parent = rootPart
		weldConstraint = Instance.new("WeldConstraint")
		weldConstraint.Parent = rootPart
	end
	rootPart.Parent = wildberryDelight
	leftHand = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://118586172794570", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	leftHand.TextureID = "rbxassetid://84063381517655"
	leftHand.CollisionGroup = "Player"
	leftHand.Name = "LeftHand"
	leftHand.CanTouch = false
	leftHand.CanQuery = false
	leftHand.Massless = true
	leftHand.CanCollide = false
	leftHand.Size = Vector3.new(0.8171, 0.2739, 0.69)
	leftHand.CFrame = CFrame.new(Vector3.new(-62.3239, 4.9043, 61.6434)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	leftHand.PivotOffset = CFrame.identity
	do
		leftHandMotor6d = Instance.new("Motor6D")
		leftHandMotor6d.Name = "LeftHandMotor6D"
		leftHandMotor6d.MaxVelocity = 0.1
		leftHandMotor6d.C0 = CFrame.new(Vector3.new(-1.763, 2.5641, -0.0655))
		leftHandMotor6d.Parent = leftHand
	end
	leftHand.Parent = wildberryDelight
end

wildberryDelight.PrimaryPart = humanoidRootPart
rightUpperArmMotor6d.Part0 = rootPart
rightUpperArmMotor6d.Part1 = rightUpperArm
leftUpperLegMotor6d.Part0 = rootPart
leftUpperLegMotor6d.Part1 = leftUpperLeg
leftMiddleLegMotor6d.Part0 = rootPart
leftMiddleLegMotor6d.Part1 = leftMiddleLeg
leftLowerArmMotor6d.Part0 = rootPart
leftLowerArmMotor6d.Part1 = leftLowerArm
rightUpperLegMotor6d.Part0 = rootPart
rightUpperLegMotor6d.Part1 = rightUpperLeg
rightLowerArmMotor6d.Part0 = rootPart
rightLowerArmMotor6d.Part1 = rightLowerArm
rightMiddleLegMotor6d.Part0 = rootPart
rightMiddleLegMotor6d.Part1 = rightMiddleLeg
tailMotor6d.Part0 = rootPart
tailMotor6d.Part1 = tail
leftUpperArmMotor6d.Part0 = rootPart
leftUpperArmMotor6d.Part1 = leftUpperArm
leftLowerLegMotor6d.Part0 = rootPart
leftLowerLegMotor6d.Part1 = leftLowerLeg
headMotor6d.Part0 = rootPart
headMotor6d.Part1 = head
torsoMotor6d.Part0 = rootPart
torsoMotor6d.Part1 = torso
leftFootMotor6d.Part0 = rootPart
leftFootMotor6d.Part1 = leftFoot
rightLowerLegMotor6d.Part0 = rootPart
rightLowerLegMotor6d.Part1 = rightLowerLeg
rightFootMotor6d.Part0 = rootPart
rightFootMotor6d.Part1 = rightFoot
rightHandMotor6d.Part0 = rootPart
rightHandMotor6d.Part1 = rightHand
weldConstraint.Part1 = rootPart
weldConstraint.Part0 = humanoidRootPart
leftHandMotor6d.Part0 = rootPart
leftHandMotor6d.Part1 = leftHand

return wildberryDelight
